//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication5.br.com.Teste {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="br.com.Teste.CursoCSharpServiceSoap")]
    public interface CursoCSharpServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetDataHoraAtualResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataHoraAtual", ReplyAction="*")]
        WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualResponse GetDataHoraAtual(WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHoraAtualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHoraAtual", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequestBody Body;
        
        public GetDataHoraAtualRequest() {
        }
        
        public GetDataHoraAtualRequest(WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataHoraAtualRequestBody {
        
        public GetDataHoraAtualRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataHoraAtualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataHoraAtualResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualResponseBody Body;
        
        public GetDataHoraAtualResponse() {
        }
        
        public GetDataHoraAtualResponse(WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataHoraAtualResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataHoraAtualResult;
        
        public GetDataHoraAtualResponseBody() {
        }
        
        public GetDataHoraAtualResponseBody(string GetDataHoraAtualResult) {
            this.GetDataHoraAtualResult = GetDataHoraAtualResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CursoCSharpServiceSoapChannel : WindowsFormsApplication5.br.com.Teste.CursoCSharpServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoCSharpServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication5.br.com.Teste.CursoCSharpServiceSoap>, WindowsFormsApplication5.br.com.Teste.CursoCSharpServiceSoap {
        
        public CursoCSharpServiceSoapClient() {
        }
        
        public CursoCSharpServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoCSharpServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoCSharpServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoCSharpServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualResponse WindowsFormsApplication5.br.com.Teste.CursoCSharpServiceSoap.GetDataHoraAtual(WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequest request) {
            return base.Channel.GetDataHoraAtual(request);
        }
        
        public string GetDataHoraAtual() {
            WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequest inValue = new WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequest();
            inValue.Body = new WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualRequestBody();
            WindowsFormsApplication5.br.com.Teste.GetDataHoraAtualResponse retVal = ((WindowsFormsApplication5.br.com.Teste.CursoCSharpServiceSoap)(this)).GetDataHoraAtual(inValue);
            return retVal.Body.GetDataHoraAtualResult;
        }
    }
}
